### ISSUE TITLE
No module named 'debug_toolbar' on manual production installation

### ISSUE THREAD

**Issue by schlamar** [sissbruecker/linkding#412]
I tried to do a manual production installation of Linkding by following the steps in `Dockerfile` and `bootstrap.sh`.

This fails at: 

```console
$ python manage.py migrate
Traceback (most recent call last):
  File "/home/marc/ld-test/linkding/manage.py", line 21, in <module>
    main()
  File "/home/marc/ld-test/linkding/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/marc/ld-test/linkding/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/marc/ld-test/linkding/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/home/marc/ld-test/linkding/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/marc/ld-test/linkding/venv/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/marc/ld-test/linkding/venv/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'debug_toolbar'
```

Workaround is `pip install django-debug-toolbar` but I'm not sure if this is the correct solution here. I tried this on different Linux distributions (Arch Linux, Cent OS 7) with the same result. I can't figure out why this works in the Docker build but not with a custom virtual environment.

Simple steps to reproduce:

```console
$ python3 -m venv venv && \
    venv/bin/python -m pip install -U pip setuptools wheel && \
    venv/bin/pip install -Ur requirements.prod.txt && \
    venv/bin/python manage.py migrate
```

**Comment by sissbruecker** [comment]
Sorry, I don't provide support manual setups. From a quick glance it looks like you are running the app in development mode.
