### ISSUE TITLE
You may need to add 'localhost' 

### ISSUE THREAD

**Issue by mrvalterhugo** [sissbruecker/linkding#431]
Hi, 

I have been using for around 2 weeks, with docker compose.

After an update, I am unable to access it.

This is the error I am getting:

```
Attaching to linkding
linkding    | Operations to perform:
linkding    |   Apply all migrations: admin, auth, authtoken, background_task, bookmarks, contenttypes, sessions
linkding    | Running migrations:
linkding    |   No migrations to apply.
linkding    | 2023-02-19 14:52:24,245 INFO Skip creating initial superuser, user already exists
linkding    | [uWSGI] getting INI configuration from uwsgi.ini
linkding    | [uwsgi-static] added mapping for /static => static
linkding    | [uwsgi-static] added mapping for /static => data/favicons
linkding    | [uwsgi-static] added mapping for /static => static
linkding    | [uwsgi-static] added mapping for /static => data/favicons
linkding    | *** Starting uWSGI 2.0.20 (64bit) on [Sun Feb 19 14:52:24 2023] ***
linkding    | compiled with version: 8.3.0 on 20 January 2023 20:30:39
linkding    | os: Linux-5.15.83-1-pve #1 SMP PVE 5.15.83-1 (2022-12-15T00:00Z)
linkding    | nodename: 9b03f3cd91d3
linkding    | machine: x86_64
linkding    | clock source: unix
linkding    | detected number of CPU cores: 4
linkding    | current working directory: /etc/linkding
linkding    | writing pidfile to /tmp/linkding.pid
linkding    | detected binary path: /opt/venv/bin/uwsgi
linkding    | !!! no internal routing support, rebuild with pcre support !!!
linkding    | setgid() to 33
linkding    | setuid() to 33
linkding    | your processes number limit is 63264
linkding    | your memory page size is 4096 bytes
linkding    | detected max file descriptor number: 524288
linkding    | building mime-types dictionary from file /etc/mime.types...565 entry found
linkding    | lock engine: pthread robust mutexes
linkding    | thunder lock: disabled (you can enable it with --thunder-lock)
linkding    | uWSGI http bound on :9090 fd 4
linkding    | uwsgi socket 0 bound to TCP address 127.0.0.1:33639 (port auto-assigned) fd 3
linkding    | Python version: 3.10.6 (main, Aug 23 2022, 08:58:52) [GCC 8.3.0]
linkding    | Python main interpreter initialized at 0x560d01234ba0
linkding    | python threads support enabled
linkding    | your server socket listen backlog is limited to 100 connections
linkding    | your mercy for graceful operations on workers is 60 seconds
linkding    | mapped 274608 bytes (268 KB) for 4 cores
linkding    | *** Operational MODE: preforking+threaded ***
linkding    | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x560d01234ba0 pid: 1 (default app)
linkding    | *** uWSGI is running in multiple interpreter mode ***
linkding    | spawned uWSGI master process (pid: 1)
linkding    | spawned uWSGI worker 1 (pid: 15, cores: 2)
linkding    | spawned uWSGI worker 2 (pid: 17, cores: 2)
linkding    | *** Stats server enabled on 127.0.0.1:9191 fd: 14 ***
linkding    | spawned uWSGI http 1 (pid: 19)
linkding    | 2023-02-19 14:52:51,556 ERROR Invalid HTTP_HOST header: 'localhost:9090'. You may need to add 'localhost' to ALLOWED_HOSTS.
linkding    | Traceback (most recent call last):
linkding    |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
linkding    |     response = get_response(request)
linkding    |   File "/opt/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
linkding    |     response = self.process_request(request)
linkding    |   File "/opt/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
linkding    |     host = request.get_host()
linkding    |   File "/opt/venv/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
linkding    |     raise DisallowedHost(msg)
linkding    | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:9090'. You may need to add 'localhost' to ALLOWED_HOSTS.
 ```

I have not changed the env file.

Is this a bug on the new image or is there a fix?

Thank You.

**Comment by sissbruecker** [comment]
Testing the latest image locally I'm not getting the error:
```
git clone git@github.com:sissbruecker/linkding.git
cd linkding
mkdir data
cp .env.sample .env
docker pull sissbruecker/linkding:latest
docker-compose up
# Open localhost:9090 in browser
```

I would guess you are using a reverse proxy? Did you change your reverse proxy settings before the update? How is it configured?

**Comment by sissbruecker** [comment]
Also you can try using the previous linkding version to check if the problem was actually introduced by the latest version: `sissbruecker/linkding:1.17.1`

**Comment by mrvalterhugo** [comment]
Hi @sissbruecker I have tested recreating it, and it seems to work when I remove the     env_file: - .env statement from the compose file.

Even when removing everything from the env file, if I specify that file, it fails.
Tested on latest and 1.17.1, and had the same issue. Not sure why it was working before.
