### ISSUE TITLE
500 Error: django.db.utils.OperationalError: database is locked

### ISSUE THREAD

**Issue by adamshand** [sissbruecker/linkding#467]
First off, I really love Linkding, it's become a fairly essential part of my tech stack.  Thanks!

However, I am getting 500 errors with some regularity.  The API seems to work flawlessly, but the web UI periodically becomes unresponsive with a 500 error.  It always resolves itself and begins working again after some minutes (I haven't timed it, but somewhere between 5-10 minutes at a guess).

Not doing anything fancy, running a fairly standard docker-compose instance with Caddy as a reverse proxy.  Can upload my `docker-compose.yml` and `.env` if that's helpful.

Today I was setting up Linkding Injector so logged into my Linkding instance and everything worked great.  Then clicked Settings" and got a 500 error. 

I don't think it's specifically a problem with the Settings page, it seems to happen randomly on any page in the UI.

Here's the errors from the logs.

```
    | 2023-05-09T22:44:44.166507623Z 2023-05-09 22:44:44,109 ERROR Internal Server Error: /settings
linkding    | 2023-05-09T22:44:44.166570410Z Traceback (most recent call last):
linkding    | 2023-05-09T22:44:44.166617470Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
linkding    | 2023-05-09T22:44:44.166632301Z     return self._session_cache
linkding    | 2023-05-09T22:44:44.166643580Z AttributeError: 'SessionStore' object has no attribute '_session_cache'
linkding    | 2023-05-09T22:44:44.166654565Z
linkding    | 2023-05-09T22:44:44.166665033Z During handling of the above exception, another exception occurred:
linkding    | 2023-05-09T22:44:44.166675797Z
linkding    | 2023-05-09T22:44:44.166686161Z Traceback (most recent call last):
linkding    | 2023-05-09T22:44:44.166696655Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
linkding    | 2023-05-09T22:44:44.166708238Z     return self.cursor.execute(sql, params)
linkding    | 2023-05-09T22:44:44.166718785Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
linkding    | 2023-05-09T22:44:44.166730709Z     return Database.Cursor.execute(self, query, params)
linkding    | 2023-05-09T22:44:44.166741524Z sqlite3.OperationalError: database is locked
linkding    | 2023-05-09T22:44:44.166752486Z
linkding    | 2023-05-09T22:44:44.166762866Z The above exception was the direct cause of the following exception:
linkding    | 2023-05-09T22:44:44.166773263Z
linkding    | 2023-05-09T22:44:44.166783179Z Traceback (most recent call last):
linkding    | 2023-05-09T22:44:44.166792935Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
linkding    | 2023-05-09T22:44:44.166803315Z     response = get_response(request)
linkding    | 2023-05-09T22:44:44.166814167Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
linkding    | 2023-05-09T22:44:44.166825362Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
linkding    | 2023-05-09T22:44:44.166835372Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
linkding    | 2023-05-09T22:44:44.166846033Z     if test_func(request.user):
linkding    | 2023-05-09T22:44:44.166856330Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 51, in <lambda>
linkding    | 2023-05-09T22:44:44.166867285Z     lambda u: u.is_authenticated,
linkding    | 2023-05-09T22:44:44.166876733Z   File "/opt/venv/lib/python3.10/site-packages/django/utils/functional.py", line 266, in inner
linkding    | 2023-05-09T22:44:44.166886722Z     self._setup()
linkding    | 2023-05-09T22:44:44.166895686Z   File "/opt/venv/lib/python3.10/site-packages/django/utils/functional.py", line 419, in _setup
linkding    | 2023-05-09T22:44:44.166905492Z     self._wrapped = self._setupfunc()
linkding    | 2023-05-09T22:44:44.166914736Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
linkding    | 2023-05-09T22:44:44.166924987Z     request.user = SimpleLazyObject(lambda: get_user(request))
linkding    | 2023-05-09T22:44:44.166934381Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
linkding    | 2023-05-09T22:44:44.166963030Z     request._cached_user = auth.get_user(request)
linkding    | 2023-05-09T22:44:44.166978612Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 191, in get_user
linkding    | 2023-05-09T22:44:44.166990276Z     user_id = _get_user_session_key(request)
linkding    | 2023-05-09T22:44:44.167000319Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
linkding    | 2023-05-09T22:44:44.167011360Z     return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
linkding    | 2023-05-09T22:44:44.167021834Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 53, in __getitem__
linkding    | 2023-05-09T22:44:44.167032856Z     return self._session[key]
linkding    | 2023-05-09T22:44:44.167043220Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 192, in _get_session
linkding    | 2023-05-09T22:44:44.167054753Z     self._session_cache = self.load()
linkding    | 2023-05-09T22:44:44.167064592Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 42, in load
linkding    | 2023-05-09T22:44:44.167075634Z     s = self._get_session_from_db()
linkding    | 2023-05-09T22:44:44.167085938Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
linkding    | 2023-05-09T22:44:44.167097263Z     return self.model.objects.get(
linkding    | 2023-05-09T22:44:44.167107604Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
linkding    | 2023-05-09T22:44:44.167119304Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
linkding    | 2023-05-09T22:44:44.167130767Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 646, in get
linkding    | 2023-05-09T22:44:44.167141869Z     num = len(clone)
linkding    | 2023-05-09T22:44:44.167151985Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 376, in __len__
linkding    | 2023-05-09T22:44:44.167162462Z     self._fetch_all()
linkding    | 2023-05-09T22:44:44.167173150Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1866, in _fetch_all
linkding    | 2023-05-09T22:44:44.167184195Z     self._result_cache = list(self._iterable_class(self))
linkding    | 2023-05-09T22:44:44.167194746Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
linkding    | 2023-05-09T22:44:44.167204933Z     results = compiler.execute_sql(
linkding    | 2023-05-09T22:44:44.167214929Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
linkding    | 2023-05-09T22:44:44.167225089Z     cursor.execute(sql, params)
linkding    | 2023-05-09T22:44:44.167235519Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
linkding    | 2023-05-09T22:44:44.167246120Z     return self._execute_with_wrappers(
linkding    | 2023-05-09T22:44:44.167256601Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
linkding    | 2023-05-09T22:44:44.167270095Z     return executor(sql, params, many, context)
linkding    | 2023-05-09T22:44:44.167295750Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
linkding    | 2023-05-09T22:44:44.167306084Z     with self.db.wrap_database_errors:
linkding    | 2023-05-09T22:44:44.167315292Z   File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
linkding    | 2023-05-09T22:44:44.167325031Z     raise dj_exc_value.with_traceback(traceback) from exc_value
linkding    | 2023-05-09T22:44:44.167334385Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
linkding    | 2023-05-09T22:44:44.167344295Z     return self.cursor.execute(sql, params)
linkding    | 2023-05-09T22:44:44.167354221Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
linkding    | 2023-05-09T22:44:44.167364915Z     return Database.Cursor.execute(self, query, params)
linkding    | 2023-05-09T22:44:44.167374828Z django.db.utils.OperationalError: database is locked
linkding    | 2023-05-09T22:44:44.167853464Z [pid: 15|app: 0|req: 8400/22674] 172.30.0.73 () {58 vars in 1108 bytes} [Tue May  9 22:44:39 2023] GET /settings => generated 145 bytes in 5070 msecs (HTTP/1.1 500) 8 headers in 279 bytes (1 switches on core 0)
linkding    | 2023-05-09T22:44:44.246790973Z 2023-05-09 22:44:44,246 WARNING Not Found: /favicon.ico
linkding    | 2023-05-09T22:44:44.247123020Z [pid: 16|app: 0|req: 14111/22675] 172.30.0.73 () {54 vars in 1017 bytes} [Tue May  9 22:44:44 2023] GET /favicon.ico => generated 179 bytes in 2 msecs (HTTP/1.1 404) 8 headers in 259 bytes (1 switches on core 0)
linkding    | 2023-05-09T22:44:53.018394596Z 2023-05-09 22:44:52,957 ERROR Internal Server Error: /settings
linkding    | 2023-05-09T22:44:53.018424165Z Traceback (most recent call last):
linkding    | 2023-05-09T22:44:53.018431944Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
linkding    | 2023-05-09T22:44:53.018439085Z     return self._session_cache
linkding    | 2023-05-09T22:44:53.018443930Z AttributeError: 'SessionStore' object has no attribute '_session_cache'
linkding    | 2023-05-09T22:44:53.018448013Z
linkding    | 2023-05-09T22:44:53.018451525Z During handling of the above exception, another exception occurred:
linkding    | 2023-05-09T22:44:53.018455157Z
linkding    | 2023-05-09T22:44:53.018458606Z Traceback (most recent call last):
linkding    | 2023-05-09T22:44:53.018462234Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
linkding    | 2023-05-09T22:44:53.018466038Z     return self.cursor.execute(sql, params)
linkding    | 2023-05-09T22:44:53.018469513Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
linkding    | 2023-05-09T22:44:53.018473163Z     return Database.Cursor.execute(self, query, params)
linkding    | 2023-05-09T22:44:53.018476603Z sqlite3.OperationalError: database is locked
linkding    | 2023-05-09T22:44:53.018479947Z
linkding    | 2023-05-09T22:44:53.018483156Z The above exception was the direct cause of the following exception:
linkding    | 2023-05-09T22:44:53.018486653Z
linkding    | 2023-05-09T22:44:53.018501902Z Traceback (most recent call last):
linkding    | 2023-05-09T22:44:53.018507292Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
linkding    | 2023-05-09T22:44:53.018513548Z     response = get_response(request)
linkding    | 2023-05-09T22:44:53.018519454Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
linkding    | 2023-05-09T22:44:53.018523217Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
linkding    | 2023-05-09T22:44:53.018526761Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
linkding    | 2023-05-09T22:44:53.018530364Z     if test_func(request.user):
linkding    | 2023-05-09T22:44:53.018533753Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 51, in <lambda>
linkding    | 2023-05-09T22:44:53.018537629Z     lambda u: u.is_authenticated,
linkding    | 2023-05-09T22:44:53.018541127Z   File "/opt/venv/lib/python3.10/site-packages/django/utils/functional.py", line 266, in inner
linkding    | 2023-05-09T22:44:53.018544667Z     self._setup()
linkding    | 2023-05-09T22:44:53.018548364Z   File "/opt/venv/lib/python3.10/site-packages/django/utils/functional.py", line 419, in _setup
linkding    | 2023-05-09T22:44:53.018552047Z     self._wrapped = self._setupfunc()
linkding    | 2023-05-09T22:44:53.018555495Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
linkding    | 2023-05-09T22:44:53.018559299Z     request.user = SimpleLazyObject(lambda: get_user(request))
linkding    | 2023-05-09T22:44:53.018562790Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
linkding    | 2023-05-09T22:44:53.018566317Z     request._cached_user = auth.get_user(request)
linkding    | 2023-05-09T22:44:53.018571371Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 191, in get_user
linkding    | 2023-05-09T22:44:53.018575347Z     user_id = _get_user_session_key(request)
linkding    | 2023-05-09T22:44:53.018578861Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
linkding    | 2023-05-09T22:44:53.018583035Z     return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
linkding    | 2023-05-09T22:44:53.018588321Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 53, in __getitem__
linkding    | 2023-05-09T22:44:53.018594960Z     return self._session[key]
linkding    | 2023-05-09T22:44:53.018599841Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 192, in _get_session
linkding    | 2023-05-09T22:44:53.018605250Z     self._session_cache = self.load()
linkding    | 2023-05-09T22:44:53.018610635Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 42, in load
linkding    | 2023-05-09T22:44:53.018616382Z     s = self._get_session_from_db()
linkding    | 2023-05-09T22:44:53.018621993Z   File "/opt/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
linkding    | 2023-05-09T22:44:53.018637332Z     return self.model.objects.get(
linkding    | 2023-05-09T22:44:53.018643634Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
linkding    | 2023-05-09T22:44:53.018649074Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
linkding    | 2023-05-09T22:44:53.018654015Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 646, in get
linkding    | 2023-05-09T22:44:53.018659223Z     num = len(clone)
linkding    | 2023-05-09T22:44:53.018664363Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 376, in __len__
linkding    | 2023-05-09T22:44:53.018673528Z     self._fetch_all()
linkding    | 2023-05-09T22:44:53.018679011Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1866, in _fetch_all
linkding    | 2023-05-09T22:44:53.018685063Z     self._result_cache = list(self._iterable_class(self))
linkding    | 2023-05-09T22:44:53.018690708Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
linkding    | 2023-05-09T22:44:53.018696460Z     results = compiler.execute_sql(
linkding    | 2023-05-09T22:44:53.018702022Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
linkding    | 2023-05-09T22:44:53.018708350Z     cursor.execute(sql, params)
linkding    | 2023-05-09T22:44:53.018714099Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
linkding    | 2023-05-09T22:44:53.018719983Z     return self._execute_with_wrappers(
linkding    | 2023-05-09T22:44:53.018725444Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
linkding    | 2023-05-09T22:44:53.018733005Z     return executor(sql, params, many, context)
linkding    | 2023-05-09T22:44:53.018738648Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
linkding    | 2023-05-09T22:44:53.018744328Z     with self.db.wrap_database_errors:
linkding    | 2023-05-09T22:44:53.018749826Z   File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
linkding    | 2023-05-09T22:44:53.018754768Z     raise dj_exc_value.with_traceback(traceback) from exc_value
linkding    | 2023-05-09T22:44:53.018760498Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
linkding    | 2023-05-09T22:44:53.018766130Z     return self.cursor.execute(sql, params)
linkding    | 2023-05-09T22:44:53.018769555Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
linkding    | 2023-05-09T22:44:53.018773143Z     return Database.Cursor.execute(self, query, params)
linkding    | 2023-05-09T22:44:53.018776522Z django.db.utils.OperationalError: database is locked
linkding    | 2023-05-09T22:44:53.019018243Z [pid: 16|app: 0|req: 14112/22676] 172.30.0.73 () {58 vars in 1087 bytes} [Tue May  9 22:44:47 2023] GET /settings => generated 145 bytes in 5074 msecs (HTTP/1.1 500) 8 headers in 279 bytes (1 switches on core 1)
```

**Comment by sissbruecker** [comment]
The logs look very similar to https://github.com/sissbruecker/linkding/issues/373, so I'll close in favor of that.
