### ISSUE TITLE
Upgraded to latest Docker image and still getting: sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by adamshand** [sissbruecker/linkding#483]
Upgraded to latest docker and still getting database is locked errors.  

Everything seemed to work after the upgrade last night.  This morning I tried to log into the web interfacer and got the below errors.  Errors happened when trying to login via web or API.

Restarting the container (docker-compose down && docker-compose up) didn't fix it.  Tried twice.

Then stopped the container made sure there were no hung processes (there weren't), checked the sqlite database manually (no problems I could see) and restarted the container.  First tried connecting via the API using the linkding Chrome extension and then logging into the web interface and it now seems to work fine.

```
❯ dcdu
Stopping linkding ... done
Removing linkding ... done
Network caddy is external, skipping
Creating linkding ... done
Attaching to linkding
linkding    | 2023-05-30T22:28:19.001675550Z Operations to perform:
linkding    | 2023-05-30T22:28:19.001730011Z   Apply all migrations: admin, auth, authtoken, background_task, bookmarks, contenttypes, sessions
linkding    | 2023-05-30T22:28:19.001742839Z Running migrations:
linkding    | 2023-05-30T22:28:19.001749672Z   No migrations to apply.
linkding    | 2023-05-30T22:28:21.653588327Z 2023-05-30 22:28:21,653 INFO Skip creating initial superuser, LD_SUPERUSER_NAME option is not defined
linkding    | 2023-05-30T22:28:22.151219222Z [uWSGI] getting INI configuration from uwsgi.ini
linkding    | 2023-05-30T22:28:22.151415616Z [uwsgi-static] added mapping for /static => static
linkding    | 2023-05-30T22:28:22.151462211Z [uwsgi-static] added mapping for /static => data/favicons
linkding    | 2023-05-30T22:28:22.151494928Z [uwsgi-static] added mapping for /static => static
linkding    | 2023-05-30T22:28:22.151521285Z [uwsgi-static] added mapping for /static => data/favicons
linkding    | 2023-05-30T22:28:22.151631078Z *** Starting uWSGI 2.0.20 (64bit) on [Tue May 30 22:28:22 2023] ***
linkding    | 2023-05-30T22:28:22.151648955Z compiled with version: 8.3.0 on 20 May 2023 09:57:29
linkding    | 2023-05-30T22:28:22.151657226Z os: Linux-5.16.0-6-amd64 #1 SMP PREEMPT Debian 5.16.18-1 (2022-03-29)
linkding    | 2023-05-30T22:28:22.151663673Z nodename: 44ccbbe491a9
linkding    | 2023-05-30T22:28:22.151670265Z machine: x86_64
linkding    | 2023-05-30T22:28:22.151701000Z clock source: unix
linkding    | 2023-05-30T22:28:22.151709313Z detected number of CPU cores: 4
linkding    | 2023-05-30T22:28:22.151716070Z current working directory: /etc/linkding
linkding    | 2023-05-30T22:28:22.151722962Z writing pidfile to /tmp/linkding.pid
linkding    | 2023-05-30T22:28:22.151845877Z detected binary path: /opt/venv/bin/uwsgi
linkding    | 2023-05-30T22:28:22.151856843Z !!! no internal routing support, rebuild with pcre support !!!
linkding    | 2023-05-30T22:28:22.151877792Z setgid() to 33
linkding    | 2023-05-30T22:28:22.152122454Z setuid() to 33
linkding    | 2023-05-30T22:28:22.152141393Z your memory page size is 4096 bytes
linkding    | 2023-05-30T22:28:22.152305912Z detected max file descriptor number: 1048576
linkding    | 2023-05-30T22:28:22.153160777Z building mime-types dictionary from file /etc/mime.types...565 entry found
linkding    | 2023-05-30T22:28:22.153225868Z lock engine: pthread robust mutexes
linkding    | 2023-05-30T22:28:22.153399356Z thunder lock: disabled (you can enable it with --thunder-lock)
linkding    | 2023-05-30T22:28:22.154303034Z uWSGI http bound on :9090 fd 4
linkding    | 2023-05-30T22:28:22.154321444Z uwsgi socket 0 bound to TCP address 127.0.0.1:42989 (port auto-assigned) fd 3
linkding    | 2023-05-30T22:28:22.154433054Z Python version: 3.10.6 (main, Aug 23 2022, 08:58:52) [GCC 8.3.0]
linkding    | 2023-05-30T22:28:22.176200773Z Python main interpreter initialized at 0x5609b955bdc0
linkding    | 2023-05-30T22:28:22.176224270Z python threads support enabled
linkding    | 2023-05-30T22:28:22.176251087Z your server socket listen backlog is limited to 100 connections
linkding    | 2023-05-30T22:28:22.176267633Z your mercy for graceful operations on workers is 60 seconds
linkding    | 2023-05-30T22:28:22.177072512Z mapped 274608 bytes (268 KB) for 4 cores
linkding    | 2023-05-30T22:28:22.177434045Z *** Operational MODE: preforking+threaded ***
linkding    | 2023-05-30T22:28:22.993559507Z WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5609b955bdc0 pid: 1 (default app)
linkding    | 2023-05-30T22:28:22.993583670Z *** uWSGI is running in multiple interpreter mode ***
linkding    | 2023-05-30T22:28:22.993593990Z spawned uWSGI master process (pid: 1)
linkding    | 2023-05-30T22:28:22.995351534Z spawned uWSGI worker 1 (pid: 15, cores: 2)
linkding    | 2023-05-30T22:28:22.996884029Z spawned uWSGI worker 2 (pid: 16, cores: 2)
linkding    | 2023-05-30T22:28:22.997046173Z *** Stats server enabled on 127.0.0.1:9191 fd: 14 ***
linkding    | 2023-05-30T22:28:22.998769204Z spawned uWSGI http 1 (pid: 18)
linkding    | 2023-05-30T22:28:38.389795894Z 2023-05-30 22:28:38,318 ERROR Internal Server Error: /api/bookmarks/
linkding    | 2023-05-30T22:28:38.389828293Z Traceback (most recent call last):
linkding    | 2023-05-30T22:28:38.389852830Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
linkding    | 2023-05-30T22:28:38.389862540Z     return self.cursor.execute(sql, params)
linkding    | 2023-05-30T22:28:38.389870137Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
linkding    | 2023-05-30T22:28:38.389877363Z     return Database.Cursor.execute(self, query, params)
linkding    | 2023-05-30T22:28:38.389884110Z sqlite3.OperationalError: database is locked
linkding    | 2023-05-30T22:28:38.389890533Z
linkding    | 2023-05-30T22:28:38.389897338Z The above exception was the direct cause of the following exception:
linkding    | 2023-05-30T22:28:38.389903636Z
linkding    | 2023-05-30T22:28:38.389909433Z Traceback (most recent call last):
linkding    | 2023-05-30T22:28:38.389915749Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
linkding    | 2023-05-30T22:28:38.389922266Z     response = get_response(request)
linkding    | 2023-05-30T22:28:38.389928546Z   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
linkding    | 2023-05-30T22:28:38.389935285Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
linkding    | 2023-05-30T22:28:38.389941839Z   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
linkding    | 2023-05-30T22:28:38.389948739Z     return view_func(*args, **kwargs)
linkding    | 2023-05-30T22:28:38.389955053Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
linkding    | 2023-05-30T22:28:38.389961471Z     return self.dispatch(request, *args, **kwargs)
linkding    | 2023-05-30T22:28:38.389967618Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
linkding    | 2023-05-30T22:28:38.389973981Z     response = self.handle_exception(exc)
linkding    | 2023-05-30T22:28:38.389980138Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
linkding    | 2023-05-30T22:28:38.389986695Z     self.raise_uncaught_exception(exc)
linkding    | 2023-05-30T22:28:38.390003590Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
linkding    | 2023-05-30T22:28:38.390033451Z     raise exc
linkding    | 2023-05-30T22:28:38.390040843Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
linkding    | 2023-05-30T22:28:38.390047241Z     self.initial(request, *args, **kwargs)
linkding    | 2023-05-30T22:28:38.390053344Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
linkding    | 2023-05-30T22:28:38.390059904Z     self.perform_authentication(request)
linkding    | 2023-05-30T22:28:38.390066550Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
linkding    | 2023-05-30T22:28:38.390073342Z     request.user
linkding    | 2023-05-30T22:28:38.391022665Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/request.py", line 227, in user
linkding    | 2023-05-30T22:28:38.391086496Z     self._authenticate()
linkding    | 2023-05-30T22:28:38.391121510Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/request.py", line 380, in _authenticate
linkding    | 2023-05-30T22:28:38.391134999Z     user_auth_tuple = authenticator.authenticate(self)
linkding    | 2023-05-30T22:28:38.391142319Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/authentication.py", line 196, in authenticate
linkding    | 2023-05-30T22:28:38.391149606Z     return self.authenticate_credentials(token)
linkding    | 2023-05-30T22:28:38.391195473Z   File "/opt/venv/lib/python3.10/site-packages/rest_framework/authentication.py", line 201, in authenticate_credentials
linkding    | 2023-05-30T22:28:38.391206176Z     token = model.objects.select_related('user').get(key=key)
linkding    | 2023-05-30T22:28:38.391212928Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 646, in get
linkding    | 2023-05-30T22:28:38.391220336Z     num = len(clone)
linkding    | 2023-05-30T22:28:38.391226980Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 376, in __len__
linkding    | 2023-05-30T22:28:38.391274376Z     self._fetch_all()
linkding    | 2023-05-30T22:28:38.391285062Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
linkding    | 2023-05-30T22:28:38.391292601Z     self._result_cache = list(self._iterable_class(self))
linkding    | 2023-05-30T22:28:38.391299727Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
linkding    | 2023-05-30T22:28:38.391350462Z     results = compiler.execute_sql(
linkding    | 2023-05-30T22:28:38.391361760Z   File "/opt/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
linkding    | 2023-05-30T22:28:38.391369511Z     cursor.execute(sql, params)
linkding    | 2023-05-30T22:28:38.391409479Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
linkding    | 2023-05-30T22:28:38.391430367Z     return self._execute_with_wrappers(
linkding    | 2023-05-30T22:28:38.391536286Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
linkding    | 2023-05-30T22:28:38.391977495Z     return executor(sql, params, many, context)
linkding    | 2023-05-30T22:28:38.391997460Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
linkding    | 2023-05-30T22:28:38.392006997Z     with self.db.wrap_database_errors:
linkding    | 2023-05-30T22:28:38.392014435Z   File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
linkding    | 2023-05-30T22:28:38.392122553Z     raise dj_exc_value.with_traceback(traceback) from exc_value
linkding    | 2023-05-30T22:28:38.392131403Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
linkding    | 2023-05-30T22:28:38.392138725Z     return self.cursor.execute(sql, params)
linkding    | 2023-05-30T22:28:38.392145607Z   File "/opt/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
linkding    | 2023-05-30T22:28:38.392154411Z     return Database.Cursor.execute(self, query, params)
linkding    | 2023-05-30T22:28:38.392162214Z django.db.utils.OperationalError: database is locked
linkding    | 2023-05-30T22:28:38.392169702Z [pid: 16|app: 0|req: 2/1] 172.30.0.73 () {54 vars in 991 bytes} [Tue May 30 22:28:33 2023] GET /api/bookmarks/?limit=1 => generated 145 bytes in 5326 msecs (HTTP/1.1 500) 8 headers in 279 bytes (1 switches on core 0)
```

**Comment by sissbruecker** [comment]
The fix is not released yet. Please watch the Github releases and try again after the next release.
