### ISSUE TITLE
Error on snapshot creation

### ISSUE THREAD

**Issue by jdckr** [sissbruecker/linkding#761]
Hi,

Snapshot creation doesn't work on my side. There is just a error message in the log without further details.

```
2024-06-17 07:32:09,439 INFO Executing bookmarks.services.tasks._schedule_html_snapshots_task: 9fca67f9-f046-43fd-861d-c401fd2d009d 
2024-06-17 07:32:09,447 INFO Create HTML snapshot for bookmark. url=https://github.com/sissbruecker/linkding
  fetch failed URL: https://github.com/sissbruecker/linkding        Stack: TypeError: fetch failed
at node:internal/deps/undici/undici:12502:13
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
               at async file:///usr/lib/node_modules/single-file-cli/node_modules/simple-cdp/mod.js:214:24
 at async retryConnection (file:///usr/lib/node_modules/single-file-cli/node_modules/simple-cdp/mod.js:237:16)
 at async Module.getPageData (file:///usr/lib/node_modules/single-file-cli/lib/cdp-client.js:49:16)
            at async capturePage (file:///usr/lib/node_modules/single-file-cli/single-file-cli-api.js:265:20)
             at async runNextTask (file:///usr/lib/node_modules/single-file-cli/single-file-cli-api.js:178:20)
             at async Promise.all (index 0)
              at async capture (file:///usr/lib/node_modules/single-file-cli/single-file-cli-api.js:129:2)
at async run (file:///usr/lib/node_modules/single-file-cli/single-file-launcher.js:85:3)
2024-06-17 07:32:32,485 ERROR Failed to HTML snapshot for bookmark. url=https://github.com/sissbruecker/linkding
Traceback (most recent call last):
            File "/etc/linkding/bookmarks/services/tasks.py", line 363, in _create_html_snapshot_task
     singlefile.create_snapshot(asset.bookmark.url, filepath)        File "/etc/linkding/bookmarks/services/singlefile2024-06-17.py", line 34, in create_snapshot
            raise SingeFileError("Failed to create snapshot")             bookmarks.services.singlefile.SingeFileError: Failed to create snapshot
2024-06-17 07:32:32,654 INFO bookmarks.services.tasks._schedule_html_snapshots_task: 9fca67f9-f046-43fd-861d-c401fd2d009d executed in 23.215s
2024-06-17 07:33:01,392 INFO Enqueueing periodic task bookmarks.services.tasks._schedule_html_snapshots_task: 3eb6f418-8a0b-4987-bc25-5cb014de397c.
2024-06-17 07:33:01,661 INFO Executing bookmarks.services.tasks._schedule_html_snapshots_task: 3eb6f418-8a0b-4987-bc25-5cb014de397c 
2024-06-17 07:33:01,673 INFO bookmarks.services.tasks._schedule_html_snapshots_task: 3eb6f418-8a0b-4987-bc25-5cb014de397c executed in 0.011s
2024-06-17 07:34:01,391 INFO Enqueueing periodic task bookmarks.services.tasks._schedule_html_snapshots_task: 241f3f5d-ccfe-4dcc-aa8e-44a9cfd9cf4f.
2024-06-17 07:34:05,392 INFO Executing bookmarks.services.tasks._schedule_html_snapshots_task: 241f3f5d-ccfe-4dcc-aa8e-44a9cfd9cf4f 
2024-06-17 07:34:05,396 INFO bookmarks.services.tasks._schedule_html_snapshots_task: 241f3f5d-ccfe-4dcc-aa8e-44a9cfd9cf4f executed in 0.003s
2024-06-17 07:35:01,391 INFO Enqueueing periodic task bookmarks.services.tasks._schedule_html_snapshots_task: 762d9ccc-ef16-412b-951b-0302f6638301.
2024-06-17 07:35:06,384 INFO Executing bookmarks.services.tasks._schedule_html_snapshots_task: 762d9ccc-ef16-412b-951b-0302f6638301 
2024-06-17 07:35:06,390 INFO bookmarks.services.tasks._schedule_html_snapshots_task: 762d9ccc-ef16-412b-951b-0302f6638301 executed in 0.005s
2024-06-17 07:36:01,392 INFO Enqueueing periodic task bookmarks.services.tasks._schedule_html_snapshots_task: d271f646-3132-4418-82c2-8e0d34690db3.
2024-06-17 07:36:09,116 INFO Executing bookmarks.services.tasks._schedule_html_snapshots_task: d271f646-3132-4418-82c2-8e0d34690db3 
2024-06-17 07:36:09,122 INFO bookmarks.services.tasks._schedule_html_snapshots_task: d271f646-3132-4418-82c2-8e0d34690db3 executed in 0.005s
2024-06-17 07:37:01,391 INFO Enqueueing periodic task bookmarks.services.tasks._schedule_html_snapshots_task: d307a210-2cf8-4203-803c-f334d505acea.
2024-06-17 07:37:02,842 INFO Executing bookmarks.services.tasks._schedule_html_snapshots_task: d307a210-2cf8-4203-803c-f334d505acea 
2024-06-17 07:37:02,847 INFO bookmarks.services.tasks._schedule_html_snapshots_task: d307a210-2cf8-4203-803c-f334d505acea executed in 0.005s
2024-06-17 07:38:01,391 INFO Enqueueing periodic task bookmarks.services.tasks._schedule_html_snapshots_task: 65b2be77-4c73-4566-9f9e-bbf03604a321.
2024-06-17 07:38:06,568 INFO Executing bookmarks.services.tasks._schedule_html_snapshots_task: 65b2be77-4c73-4566-9f9e-bbf03604a321 
2024-06-17 07:38:06,576 INFO bookmarks.services.tasks._schedule_html_snapshots_task: 65b2be77-4c73-4566-9f9e-bbf03604a321 executed in 0.008s
```

Thanks for the great app.

Cheers.

**Comment by sissbruecker** [comment]
What's the URL you're trying to create a snapshot for?

**Comment by jdckr** [comment]
Tried several urls. As listed in the log above, I used `https://github.com/sissbruecker/linkding` to create the error case.

I anyway migrated from a Raspberry Pi4 to a Dell Wyse 5070 in the meantime and don't have a problem with snapshot creation anymore.

Ticket can be closed.
