### ISSUE TITLE
Cant create snapshots

### ISSUE THREAD

**Issue by Just4Link** [sissbruecker/linkding#817]
When i try to create a HTML snapshots for whatever website i got a snapshot failed after 60 second. I tried already to increase the time to 120 but no success. Everything else is working fine.

Here from my docker compose:

app:
   image: "sissbruecker/linkding:latest-plus"
   container_name: "linkding"
   depends_on:
     db:
       condition: service_healthy
   volumes:
     - type: volume
       source: "linkding_app_data"
       target: "/etc/linkding/data"
       read_only: false
   networks:
     backend:
       ipv4_address: 172.30.45.2
     frontend:
       ipv4_address: 172.30.46.2
   ports:
     - target: 9090
       published: 9090
       protocol: tcp
       mode: host
   environment:
     # Zeitzone
    TZ: "Europe/Berlin"
     LD_DISABLE_URL_VALIDATION: "False"
     LD_ENABLE_AUTH_PROXY: "False"
    LD_LOG_X_FORWARDED_FOR: "true"
    LD_CSRF_TRUSTED_ORIGINS: "https://linkding.home.local"
   # Datenbank
   LD_DB_ENGINE: "postgres"
   LD_DB_HOST: "db"
   #LD_DB_PORT: ""
   #LD_DB_OPTIONS: ""
   LD_DB_DATABASE: "linkding_db"
   LD_DB_USER: "linkding"
   LD_DB_PASSWORD: "linkding"
  restart: always

Here my logs from pressing the snapshot button till the subprocess exit

2024-09-08T16:13:29.032695393Z [pid: 19|app: 0|req: 145/372] 192.168.20.10 () {56 vars in 1047 bytes} [Sun Sep  8 18:13:29 2024] GET /bookmarks/4/details_assets => generated 1611 bytes in 18 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:13:29.127711771Z [pid: 19|app: 0|req: 146/373] 192.168.20.10 () {60 vars in 1241 bytes} [Sun Sep  8 18:13:29 2024] GET /admin/tasks/ => generated 8339 bytes in 19 msecs (HTTP/1.1 200) 9 headers in 397 bytes (1 switches on core 0)
2024-09-08T16:13:35.219625524Z [pid: 21|app: 0|req: 207/374] 192.168.20.10 () {46 vars in 971 bytes} [Sun Sep  8 18:13:35 2024] GET /api/bookmarks/?q=linkding%20subprocess%20exited%20with%20code%200&limit=10 => generated 52 bytes in 19 msecs (HTTP/1.1 200) 9 headers in 292 bytes (1 switches on core 1)
2024-09-08T16:13:44.702668097Z [pid: 19|app: 0|req: 147/375] 127.0.0.1 () {28 vars in 306 bytes} [Sun Sep  8 18:13:44 2024] GET /health => generated 42 bytes in 10 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 1)
2024-09-08T16:13:47.963526852Z [pid: 21|app: 0|req: 208/376] 192.168.20.10 () {46 vars in 965 bytes} [Sun Sep  8 18:13:47 2024] GET /api/bookmarks/?q=linkding%20failure%20exited%20with%20code%200&limit=10 => generated 52 bytes in 20 msecs (HTTP/1.1 200) 9 headers in 292 bytes (1 switches on core 0)
2024-09-08T16:13:56.922359193Z [pid: 19|app: 0|req: 148/377] 192.168.20.10 () {46 vars in 910 bytes} [Sun Sep  8 18:13:56 2024] GET /api/bookmarks/?q=linkding%20failure&limit=10 => generated 52 bytes in 19 msecs (HTTP/1.1 200) 9 headers in 292 bytes (1 switches on core 0)
2024-09-08T16:14:14.756912808Z [pid: 19|app: 0|req: 149/378] 127.0.0.1 () {28 vars in 306 bytes} [Sun Sep  8 18:14:14 2024] GET /health => generated 42 bytes in 9 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 1)
2024-09-08T16:14:44.816752578Z [pid: 21|app: 0|req: 209/379] 127.0.0.1 () {28 vars in 306 bytes} [Sun Sep  8 18:14:44 2024] GET /health => generated 42 bytes in 10 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 1)
2024-09-08T16:15:14.876314256Z [pid: 21|app: 0|req: 210/380] 127.0.0.1 () {28 vars in 306 bytes} [Sun Sep  8 18:15:14 2024] GET /health => generated 42 bytes in 10 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 0)
2024-09-08T16:15:31.533002456Z [pid: 21|app: 0|req: 211/381] 192.168.20.10 () {56 vars in 1090 bytes} [Sun Sep  8 18:15:31 2024] GET /bookmarks/2/details_modal?return_url=/bookmarks => generated 7860 bytes in 20 msecs (HTTP/1.1 200) 9 headers in 397 bytes (1 switches on core 1)
2024-09-08T16:15:34.325695914Z [pid: 19|app: 0|req: 150/382] 192.168.20.10 () {62 vars in 1188 bytes} [Sun Sep  8 18:15:34 2024] POST /bookmarks/2/details => generated 0 bytes in 27 msecs (HTTP/1.1 302) 9 headers in 293 bytes (1 switches on core 0)
2024-09-08T16:15:34.353537275Z [pid: 19|app: 0|req: 152/383] 192.168.20.10 () {56 vars in 1067 bytes} [Sun Sep  8 18:15:34 2024] GET /bookmarks/partials/tag-cloud/active => generated 71 bytes in 22 msecs (HTTP/1.1 200) 8 headers in 259 bytes (1 switches on core 0)
2024-09-08T16:15:34.354874168Z [pid: 19|app: 0|req: 152/384] 192.168.20.10 () {56 vars in 1047 bytes} [Sun Sep  8 18:15:34 2024] GET /bookmarks/2/details_modal => generated 9092 bytes in 23 msecs (HTTP/1.1 200) 9 headers in 397 bytes (1 switches on core 1)
2024-09-08T16:15:34.355400083Z [pid: 21|app: 0|req: 212/385] 192.168.20.10 () {56 vars in 1075 bytes} [Sun Sep  8 18:15:34 2024] GET /bookmarks/partials/bookmark-list/active => generated 8758 bytes in 24 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:15:39.382386102Z [pid: 21|app: 0|req: 213/386] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:15:39 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:15:44.421619408Z [pid: 21|app: 0|req: 214/387] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:15:44 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 20 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:15:44.936645596Z [pid: 19|app: 0|req: 153/388] 127.0.0.1 () {28 vars in 306 bytes} [Sun Sep  8 18:15:44 2024] GET /health => generated 42 bytes in 10 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 0)
2024-09-08T16:15:49.456382554Z [pid: 19|app: 0|req: 154/389] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:15:49 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:15:54.483306181Z [pid: 21|app: 0|req: 215/390] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:15:54 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:15:59.518580982Z [pid: 19|app: 0|req: 155/391] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:15:59 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 21 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:16:04.561375802Z [pid: 19|app: 0|req: 156/392] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:04 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 20 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:16:09.584127018Z [pid: 21|app: 0|req: 216/393] 192.168.20.10 () {56 vars in 1047 bytes} [Sun Sep  8 18:16:09 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 16 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:16:14.612020277Z [pid: 21|app: 0|req: 217/394] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:14 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 18 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:16:15.002257380Z [pid: 21|app: 0|req: 218/395] 127.0.0.1 () {28 vars in 306 bytes} [Sun Sep  8 18:16:14 2024] GET /health => generated 42 bytes in 10 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 0)
2024-09-08T16:16:19.639204347Z [pid: 21|app: 0|req: 219/396] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:19 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:16:24.675576095Z [pid: 21|app: 0|req: 220/397] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:24 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 18 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:16:29.702369857Z [pid: 21|app: 0|req: 221/398] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:29 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 18 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:16:34.726093969Z [pid: 21|app: 0|req: 222/399] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:34 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 17 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:16:39.762964595Z [pid: 19|app: 0|req: 157/400] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:39 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 21 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:16:44.801537138Z [pid: 21|app: 0|req: 223/401] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:44 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 20 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:16:45.058605313Z [pid: 19|app: 0|req: 158/402] 127.0.0.1 () {28 vars in 306 bytes} [Sun Sep  8 18:16:45 2024] GET /health => generated 42 bytes in 10 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 1)
2024-09-08T16:16:49.838228303Z [pid: 21|app: 0|req: 224/403] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:49 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 16 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:16:54.862708837Z [pid: 19|app: 0|req: 159/404] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:54 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 18 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:16:59.886580797Z [pid: 21|app: 0|req: 225/405] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:16:59 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 18 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:17:04.927298163Z [pid: 19|app: 0|req: 160/406] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:04 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:17:09.965025811Z [pid: 21|app: 0|req: 226/407] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:09 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:17:15.005509809Z [pid: 21|app: 0|req: 227/408] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:14 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:17:15.125556542Z [pid: 21|app: 0|req: 228/409] 127.0.0.1 () {28 vars in 306 bytes} [Sun Sep  8 18:17:15 2024] GET /health => generated 42 bytes in 10 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 0)
2024-09-08T16:17:20.040221497Z [pid: 21|app: 0|req: 229/410] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:20 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 22 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:17:25.065986563Z [pid: 19|app: 0|req: 161/411] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:25 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:17:30.104170913Z [pid: 19|app: 0|req: 162/412] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:30 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 24 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:17:35.132983982Z [pid: 19|app: 0|req: 163/413] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:35 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 18 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:17:40.163792657Z [pid: 21|app: 0|req: 230/414] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:40 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 18 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:17:45.190788559Z [pid: 19|app: 0|req: 164/415] 127.0.0.1 () {28 vars in 306 bytes} [Sun Sep  8 18:17:45 2024] GET /health => generated 42 bytes in 11 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 1)
2024-09-08T16:17:45.194912132Z [pid: 21|app: 0|req: 231/416] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:45 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 23 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:17:50.223693159Z [pid: 19|app: 0|req: 165/417] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:50 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 21 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:17:55.251133317Z [pid: 19|app: 0|req: 166/418] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:17:55 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 18 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:18:00.290839974Z [pid: 21|app: 0|req: 232/419] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:18:00 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 21 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:18:05.319410630Z [pid: 21|app: 0|req: 233/420] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:18:05 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:18:10.344838845Z [pid: 21|app: 0|req: 234/421] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:18:10 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 17 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:18:15.255815753Z [pid: 21|app: 0|req: 235/422] 127.0.0.1 () {28 vars in 305 bytes} [Sun Sep  8 18:18:15 2024] GET /health => generated 42 bytes in 10 msecs (HTTP/1.1 200) 8 headers in 251 bytes (1 switches on core 1)
2024-09-08T16:18:15.382939905Z [pid: 19|app: 0|req: 167/423] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:18:15 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:18:20.413925490Z [pid: 21|app: 0|req: 236/424] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:18:20 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 19 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 0)
2024-09-08T16:18:25.440768502Z [pid: 21|app: 0|req: 237/425] 192.168.20.10 () {56 vars in 1049 bytes} [Sun Sep  8 18:18:25 2024] GET /bookmarks/2/details_assets => generated 3962 bytes in 16 msecs (HTTP/1.1 200) 8 headers in 261 bytes (1 switches on core 1)
2024-09-08T16:18:26.869350470Z subprocess 1373 exited with code 0
2024-09-08T16:18:26.869384574Z subprocess 1375 exited with code 0
2024-09-08T16:18:26.869388481Z subprocess 1378 exited with code 0
2024-09-08T16:18:26.869391947Z subprocess 1379 exited with code 0
2024-09-08T16:18:26.869501565Z subprocess 1400 exited with code 0
2024-09-08T16:18:26.869511654Z subprocess 1406 exited with code 0
2024-09-08T16:18:26.869548363Z subprocess 1457 exited with code 0

**Comment by sissbruecker** [comment]
Please check `background_tasks.log` in the Docker container for snapshot logs and provide some specific URLs that failed.

**Comment by Just4Link** [comment]
Here my log from the backgroundtask_log. That is for google.com

2024-09-09 10:30:17,310 INFO Enqueueing periodic task bookmarks.services.tasks._schedule_html_snapshots_task: a28948db-eb9d-4b49-a779-057ae6ec69c6.
2024-09-09 10:30:23,527 INFO Executing bookmarks.services.tasks._schedule_html_snapshots_task: a28948db-eb9d-4b49-a779-057ae6ec69c6
2024-09-09 10:30:23,528 ERROR Unhandled exception in task a28948db-eb9d-4b49-a779-057ae6ec69c6.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 294, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 332, in create_cursor
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/huey/api.py", line 382, in _execute
    task_value = task.execute()
                 ^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/huey/api.py", line 807, in execute
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/huey/api.py", line 905, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/etc/linkding/bookmarks/services/tasks.py", line 303, in _schedule_html_snapshots_task
    for asset in assets:
  File "/opt/venv/lib/python3.11/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
  File "/opt/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 316, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 293, in _cursor
    with self.wrap_database_errors:
  File "/opt/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 294, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 332, in create_cursor
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.InterfaceError: connection already closed

**Comment by cirrusflyer** [comment]
I'm seeing the same behavior, and reported here too:  https://github.com/sissbruecker/linkding/issues/803

**Comment by Just4Link** [comment]
Today i just scrolled through my bookmarks and saw that snapshots were available without error checkmarks. Seems with the last update there was something fixed.

I created a bunch of bookmarks and let creating snapshots. So far everything works now.

Have a nice day and thank you for this helpful project.
